window.esdocSearchIndex = [
  [
    "./source/components/app/appcontainer.js~appcontainer",
    "variable/index.html#static-variable-AppContainer",
    "<span>AppContainer</span> <span class=\"search-result-import-path\">./source/components/app/AppContainer.js</span>",
    "variable"
  ],
  [
    "./source/stores/appstore.js~appstore",
    "class/source/stores/AppStore.js~AppStore.html",
    "<span>AppStore</span> <span class=\"search-result-import-path\">./source/stores/AppStore.js</span>",
    "class"
  ],
  [
    "./source/components/common/erroralert.js~erroralert",
    "function/index.html#static-function-ErrorAlert",
    "<span>ErrorAlert</span> <span class=\"search-result-import-path\">./source/components/common/ErrorAlert.js</span>",
    "function"
  ],
  [
    "./source/components/error/errorboundary.js~errorboundary",
    "class/source/components/error/ErrorBoundary.js~ErrorBoundary.html",
    "<span>ErrorBoundary</span> <span class=\"search-result-import-path\">./source/components/error/ErrorBoundary.js</span>",
    "class"
  ],
  [
    "./source/components/common/header.js~header",
    "function/index.html#static-function-Header",
    "<span>Header</span> <span class=\"search-result-import-path\">./source/components/common/Header.js</span>",
    "function"
  ],
  [
    "./source/components/common/loadingscreen.js~loadingscreen",
    "function/index.html#static-function-LoadingScreen",
    "<span>LoadingScreen</span> <span class=\"search-result-import-path\">./source/components/common/LoadingScreen.js</span>",
    "function"
  ],
  [
    "./source/components/common/reactivetextfield.js~reactivetextfield",
    "class/source/components/common/ReactiveTextField.js~ReactiveTextField.html",
    "<span>ReactiveTextField</span> <span class=\"search-result-import-path\">./source/components/common/ReactiveTextField.js</span>",
    "class"
  ],
  [
    "./source/components/restaurant/restaurantlistitem.js~restaurantitem",
    "function/index.html#static-function-RestaurantItem",
    "<span>RestaurantItem</span> <span class=\"search-result-import-path\">./source/components/restaurant/RestaurantListItem.js</span>",
    "function"
  ],
  [
    "./source/components/restaurant/restaurantlistscreen.js~restaurantlistscreen",
    "class/source/components/restaurant/RestaurantListScreen.js~RestaurantListScreen.html",
    "<span>RestaurantListScreen</span> <span class=\"search-result-import-path\">./source/components/restaurant/RestaurantListScreen.js</span>",
    "class"
  ],
  [
    "./source/components/restaurant/restaurantscreen.js~restaurantscreen",
    "class/source/components/restaurant/RestaurantScreen.js~RestaurantScreen.html",
    "<span>RestaurantScreen</span> <span class=\"search-result-import-path\">./source/components/restaurant/RestaurantScreen.js</span>",
    "class"
  ],
  [
    "./source/stores/restaurantstore.js~restaurantstore",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html",
    "<span>RestaurantStore</span> <span class=\"search-result-import-path\">./source/stores/RestaurantStore.js</span>",
    "class"
  ],
  [
    "./source/components/common/styledtext.js~sourcesansprotext",
    "function/index.html#static-function-SourceSansProText",
    "<span>SourceSansProText</span> <span class=\"search-result-import-path\">./source/components/common/StyledText.js</span>",
    "function"
  ],
  [
    "./source/stores/uistore.js~uistore",
    "class/source/stores/UIStore.js~UIStore.html",
    "<span>UIStore</span> <span class=\"search-result-import-path\">./source/stores/UIStore.js</span>",
    "class"
  ],
  [
    "./source/utils/helpers.js~getdata",
    "function/index.html#static-function-getData",
    "<span>getData</span> <span class=\"search-result-import-path\">./source/utils/helpers.js</span>",
    "function"
  ],
  [
    "./source/utils/helpers.js~renderif",
    "function/index.html#static-function-renderIf",
    "<span>renderIf</span> <span class=\"search-result-import-path\">./source/utils/helpers.js</span>",
    "function"
  ],
  [
    "./source/utils/helpers.js~runinactionutil",
    "function/index.html#static-function-runInActionUtil",
    "<span>runInActionUtil</span> <span class=\"search-result-import-path\">./source/utils/helpers.js</span>",
    "function"
  ],
  [
    "./source/utils/helpers.js~setclassprops",
    "function/index.html#static-function-setClassProps",
    "<span>setClassProps</span> <span class=\"search-result-import-path\">./source/utils/helpers.js</span>",
    "function"
  ],
  [
    "./source/utils/helpers.js~truncatestring",
    "function/index.html#static-function-truncateString",
    "<span>truncateString</span> <span class=\"search-result-import-path\">./source/utils/helpers.js</span>",
    "function"
  ],
  [
    "",
    "test-file/tests/stores/one.js.html#lineNumber5",
    "Root",
    "test"
  ],
  [
    "",
    "test-file/tests/stores/one.js.html#lineNumber6",
    "Root should render correctly",
    "test"
  ],
  [
    "source/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "source/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "source/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "source/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "source/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "source/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "source/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "source/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "source/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "source/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "source/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "source/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "source/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "source/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "source/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "source/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "source/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "source/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "source/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "source/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "source/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "source/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "source/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "source/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "source/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "source/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "source/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "source/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "source/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "source/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "source/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "source/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "source/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "source/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "source/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "source/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~String",
    "external"
  ],
  [
    "source/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "source/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "source/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "source/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "source/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "source/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "source/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "source/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "source/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "source/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "source/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "source/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "source/.external-ecmascript.js~null",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~string",
    "external"
  ],
  [
    "source/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "source/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "source/assets/styles/base/global.js",
    "file/source/assets/styles/base/global.js.html",
    "source/assets/styles/base/global.js",
    "file"
  ],
  [
    "source/assets/styles/base/placeholders.js",
    "file/source/assets/styles/base/placeholders.js.html",
    "source/assets/styles/base/placeholders.js",
    "file"
  ],
  [
    "source/assets/styles/components/app.js",
    "file/source/assets/styles/components/app.js.html",
    "source/assets/styles/components/app.js",
    "file"
  ],
  [
    "source/assets/styles/components/error.js",
    "file/source/assets/styles/components/error.js.html",
    "source/assets/styles/components/error.js",
    "file"
  ],
  [
    "source/assets/styles/components/header.js",
    "file/source/assets/styles/components/header.js.html",
    "source/assets/styles/components/header.js",
    "file"
  ],
  [
    "source/assets/styles/components/restaurant.js",
    "file/source/assets/styles/components/restaurant.js.html",
    "source/assets/styles/components/restaurant.js",
    "file"
  ],
  [
    "source/components/app/appcontainer.js",
    "file/source/components/app/AppContainer.js.html",
    "source/components/app/AppContainer.js",
    "file"
  ],
  [
    "source/components/common/erroralert.js",
    "file/source/components/common/ErrorAlert.js.html",
    "source/components/common/ErrorAlert.js",
    "file"
  ],
  [
    "source/components/common/header.js",
    "file/source/components/common/Header.js.html",
    "source/components/common/Header.js",
    "file"
  ],
  [
    "source/components/common/loadingscreen.js",
    "file/source/components/common/LoadingScreen.js.html",
    "source/components/common/LoadingScreen.js",
    "file"
  ],
  [
    "source/components/common/reactivetextfield.js",
    "file/source/components/common/ReactiveTextField.js.html",
    "source/components/common/ReactiveTextField.js",
    "file"
  ],
  [
    "source/components/common/reactivetextfield.js~reactivetextfield#render",
    "class/source/components/common/ReactiveTextField.js~ReactiveTextField.html#instance-method-render",
    "source/components/common/ReactiveTextField.js~ReactiveTextField#render",
    "method"
  ],
  [
    "source/components/common/styledtext.js",
    "file/source/components/common/StyledText.js.html",
    "source/components/common/StyledText.js",
    "file"
  ],
  [
    "source/components/error/errorboundary.js",
    "file/source/components/error/ErrorBoundary.js.html",
    "source/components/error/ErrorBoundary.js",
    "file"
  ],
  [
    "source/components/error/errorboundary.js~errorboundary#componentdidcatch",
    "class/source/components/error/ErrorBoundary.js~ErrorBoundary.html#instance-method-componentDidCatch",
    "source/components/error/ErrorBoundary.js~ErrorBoundary#componentDidCatch",
    "method"
  ],
  [
    "source/components/error/errorboundary.js~errorboundary#constructor",
    "class/source/components/error/ErrorBoundary.js~ErrorBoundary.html#instance-constructor-constructor",
    "source/components/error/ErrorBoundary.js~ErrorBoundary#constructor",
    "method"
  ],
  [
    "source/components/error/errorboundary.js~errorboundary#render",
    "class/source/components/error/ErrorBoundary.js~ErrorBoundary.html#instance-method-render",
    "source/components/error/ErrorBoundary.js~ErrorBoundary#render",
    "method"
  ],
  [
    "source/components/error/errorboundary.js~errorboundary#state",
    "class/source/components/error/ErrorBoundary.js~ErrorBoundary.html#instance-member-state",
    "source/components/error/ErrorBoundary.js~ErrorBoundary#state",
    "member"
  ],
  [
    "source/components/restaurant/restaurantlistitem.js",
    "file/source/components/restaurant/RestaurantListItem.js.html",
    "source/components/restaurant/RestaurantListItem.js",
    "file"
  ],
  [
    "source/components/restaurant/restaurantlistscreen.js",
    "file/source/components/restaurant/RestaurantListScreen.js.html",
    "source/components/restaurant/RestaurantListScreen.js",
    "file"
  ],
  [
    "source/components/restaurant/restaurantlistscreen.js~restaurantlistscreen#constructor",
    "class/source/components/restaurant/RestaurantListScreen.js~RestaurantListScreen.html#instance-constructor-constructor",
    "source/components/restaurant/RestaurantListScreen.js~RestaurantListScreen#constructor",
    "method"
  ],
  [
    "source/components/restaurant/restaurantlistscreen.js~restaurantlistscreen#render",
    "class/source/components/restaurant/RestaurantListScreen.js~RestaurantListScreen.html#instance-method-render",
    "source/components/restaurant/RestaurantListScreen.js~RestaurantListScreen#render",
    "method"
  ],
  [
    "source/components/restaurant/restaurantlistscreen.js~restaurantlistscreen#renderitems",
    "class/source/components/restaurant/RestaurantListScreen.js~RestaurantListScreen.html#instance-member-renderItems",
    "source/components/restaurant/RestaurantListScreen.js~RestaurantListScreen#renderItems",
    "member"
  ],
  [
    "source/components/restaurant/restaurantscreen.js",
    "file/source/components/restaurant/RestaurantScreen.js.html",
    "source/components/restaurant/RestaurantScreen.js",
    "file"
  ],
  [
    "source/components/restaurant/restaurantscreen.js~restaurantscreen#render",
    "class/source/components/restaurant/RestaurantScreen.js~RestaurantScreen.html#instance-method-render",
    "source/components/restaurant/RestaurantScreen.js~RestaurantScreen#render",
    "method"
  ],
  [
    "source/components/restaurant/restaurantscreen.js~restaurantscreen.navigationoptions",
    "class/source/components/restaurant/RestaurantScreen.js~RestaurantScreen.html#static-member-navigationOptions",
    "source/components/restaurant/RestaurantScreen.js~RestaurantScreen.navigationOptions",
    "member"
  ],
  [
    "source/stores/appstore.js",
    "file/source/stores/AppStore.js.html",
    "source/stores/AppStore.js",
    "file"
  ],
  [
    "source/stores/appstore.js~appstore#name",
    "class/source/stores/AppStore.js~AppStore.html#instance-member-name",
    "source/stores/AppStore.js~AppStore#name",
    "member"
  ],
  [
    "source/stores/appstore.js~appstore#setclassprops",
    "class/source/stores/AppStore.js~AppStore.html#instance-member-setClassProps",
    "source/stores/AppStore.js~AppStore#setClassProps",
    "member"
  ],
  [
    "source/stores/restaurantstore.js",
    "file/source/stores/RestaurantStore.js.html",
    "source/stores/RestaurantStore.js",
    "file"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#getrestaurants",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-getRestaurants",
    "source/stores/RestaurantStore.js~RestaurantStore#getRestaurants",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#loading",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-loading",
    "source/stores/RestaurantStore.js~RestaurantStore#loading",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#onendreached",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-onEndReached",
    "source/stores/RestaurantStore.js~RestaurantStore#onEndReached",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#refreshing",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-refreshing",
    "source/stores/RestaurantStore.js~RestaurantStore#refreshing",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#restaurants",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-restaurants",
    "source/stores/RestaurantStore.js~RestaurantStore#restaurants",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#searchstring",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-searchString",
    "source/stores/RestaurantStore.js~RestaurantStore#searchString",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#searchbarref",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-searchbarRef",
    "source/stores/RestaurantStore.js~RestaurantStore#searchbarRef",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#setclassprops",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-setClassProps",
    "source/stores/RestaurantStore.js~RestaurantStore#setClassProps",
    "member"
  ],
  [
    "source/stores/restaurantstore.js~restaurantstore#showsearchbar",
    "class/source/stores/RestaurantStore.js~RestaurantStore.html#instance-member-showSearchbar",
    "source/stores/RestaurantStore.js~RestaurantStore#showSearchbar",
    "member"
  ],
  [
    "source/stores/uistore.js",
    "file/source/stores/UIStore.js.html",
    "source/stores/UIStore.js",
    "file"
  ],
  [
    "source/stores/uistore.js~uistore#name",
    "class/source/stores/UIStore.js~UIStore.html#instance-member-name",
    "source/stores/UIStore.js~UIStore#name",
    "member"
  ],
  [
    "source/stores/uistore.js~uistore#setclassprops",
    "class/source/stores/UIStore.js~UIStore.html#instance-member-setClassProps",
    "source/stores/UIStore.js~UIStore#setClassProps",
    "member"
  ],
  [
    "source/stores/index.js",
    "file/source/stores/index.js.html",
    "source/stores/index.js",
    "file"
  ],
  [
    "source/utils/helpers.js",
    "file/source/utils/helpers.js.html",
    "source/utils/helpers.js",
    "file"
  ],
  [
    "tests/stores/one.js",
    "test-file/tests/stores/one.js.html",
    "tests/stores/one.js",
    "testFile"
  ]
]